# Generated by Django 2.2.2 on 2019-06-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogueapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogueAdminPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('catalogueadmin', 'Can Admin The Catalogue'),),
                'managed': False,
            },
        ),
    ]
