# Generated by Django 2.2.3 on 2019-07-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogueapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ALISSMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribution', models.TextField(blank=True)),
                ('licence', models.TextField(blank=True)),
            ],
        ),
    ]
