# Generated by Django 2.2.3 on 2019-07-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogueapp', '0002_alissmeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='our_description_markdown',
            field=models.TextField(blank=True),
        ),
    ]
